export const CATEGORY_ES = {
  "Базовые слова": "Palabras básicas",
  "Глаголы": "Verbos",
  "Грамматика": "Gramática",
  "Деньги и экономика": "Dinero y economía",
  "Дом": "Casa",
  "Досуг и спорт": "Ocio y deporte",
  "Еда": "Comida",
  "Здоровье": "Salud",
  "Люди": "Gente",
  "Магазины и одежда": "Tiendas y ropa",
  "Общество и праздники": "Sociedad y fiestas",
  "Окружающая среда": "Medio ambiente",
  "Работа": "Trabajo",
  "Транспорт": "Transporte",
  "Учеба": "Estudios",
};

export const CATEGORY_ICON = {
  "Базовые слова": "book",
  "Глаголы": "bolt",
  "Грамматика": "pencil",
  "Деньги и экономика": "coin",
  "Дом": "home",
  "Досуг и спорт": "ball",
  "Еда": "fork",
  "Здоровье": "health",
  "Люди": "people",
  "Магазины и одежда": "bag",
  "Общество и праздники": "gift",
  "Окружающая среда": "leaf",
  "Работа": "briefcase",
  "Транспорт": "car",
  "Учеба": "cap",
};
